name: hive_module
description: "JuneFlow Module"
#publish_to: 'none'
#repository: https://github.com/melodysdreamj/juneflow

version: 1.0.0+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:

  hive: #@add
  hive_flutter: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true