name: hive_module
description: "this module is a wrapper for the hive package, it provides a simple way to use hive in juneflow project."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/hive_module

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  hive: #@add
  isar_flutter_libs: #@add
  path_provider: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true